apiVersion: v1
kind: Service
metadata:
  name: netpulse
  namespace: netpulse
  labels:
    app: netpulse
spec:
  type: ClusterIP
  selector:
    app: netpulse
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
